# Untested use SNS instead of SES to notify - generated by co-pilot

def notify(destination, username, reminder=None):
    """
    Sends a notification message using AWS SNS to inform the user about access key rotation.

    :param destination: TO email address or phone number (ARN for SMS)
    :param username: The IAM username
    :param reminder: optional if configured, this is a reminder notification
    :returns: message id if send was successful
    :raises: error if send was a failure
    """
    client = boto3.client("sns")
    topic_arn = "arn:aws:sns:REGION:ACCOUNT_ID:TOPIC_NAME"  # Replace with your SNS topic ARN

    message = (
        f"A new Access Key has been generated for {username}. "
        f"Details have been stored in Vault. Please update your use."
    )

    subject = "New access keys created" if not reminder else "Reminder: New access keys created"

    try:
        response = client.publish(
            TopicArn=topic_arn,
            Message=message,
            Subject=subject,
        )
        message_id = response["MessageId"]
        print(f"Sent notification {message_id} to {destination}")
    except Exception as e:
        print(f"Couldn't send notification to {destination}: {e}")
        raise
    else:
        return message_id
